# baseline_observed_ports_to_services.conf
# Creates a lookup of ports to services mapping from Zeek connection logs

[Baseline_Observed_Ports_to_Services]
action.email.useNSSubject = 1
alert.track = 0
cron_schedule = 0 4 * * *
description = Creates a lookup of ports to services mapping from Zeek connection logs
dispatch.earliest_time = -24h@h
dispatch.latest_time = now
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.show = 0
enableSched = 1
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = index=zeek sourcetype=bro:conn:json\
        | table id.resp_p service marked_valid\
        | dedup id.resp_p service marked_valid\
        | outputcsv Baseline_Observed_Ports_to_Services\
        | outputlookup Baseline_Observed_Ports_to_Services.csv