# baseline_domainname_clientname_clientip.conf
# Creates a lookup of domain names, client names, and client IPs from Zeek DNS and Powershell logs

[Baseline_DomainName_ClientName_ClientIP]
action.email.useNSSubject = 1
alert.track = 0
cron_schedule = 0 3 * * *
description = Creates a lookup of domain names, client names, and client IPs from Zeek DNS and Powershell logs
dispatch.earliest_time = -24h@h
dispatch.latest_time = now
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.show = 0
enableSched = 1
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = | multisearch \
    [ search index=powershell "Command.Module"=GetDomainComputers\
      | fields Data.DNSName, Data.IPAddress\
      | rex field=Data.DNSName "^(?<Client_Name>[^.]+)\.(?<Domain_Name>.+)"\
      | eval source="powershell"\
      | eval Client_IP=lower('Data.IPAddress'), Domain_Name=lower(Domain_Name), Client_Name=lower(Client_Name)\
      | fields Domain_Name, Client_IP, Client_Name, source ]\
    [ search index=zeek sourcetype="bro:dns:json" query!="*\.arpa" query!="" answers!="0.0.0.0" query!="0.0.0.0"\
      | fields query, answers\
      | rex field=answers "(?<Client_IP>\b(?:\d{1,3}\.){3}\d{1,3}\b)"\
      | rex field=query "^(?<Client_Name>[^.]+)\.(?<Domain_Name>.+)"\
      | eval source="zeek", Domain_Name=lower(Domain_Name), Client_IP=lower(Client_IP), Client_Name=lower(Client_Name)\
      | fields Domain_Name, Client_IP, Client_Name, source ]\
  | dedup Domain_Name, Client_IP, Client_Name, source\
  | table Domain_Name, Client_IP, Client_Name, source\
  | sort Client_IP\
  | outputcsv Baseline_DomainName_ClientName_ClientIP.csv\
  | outputlookup Baseline_DomainName_ClientName_ClientIP.csv