# Splunk app configuration file

[install]
is_configured = 0

[ui]
is_visible = 1
label = MITRE CAR

[launcher]
author = get-sybers
description = MITRE Cyber Analytics Repository data model, and the field mappings that populate it from this pipeline's sources.
version = 0.2.0
