---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    dfir_deploy_adx_container: kusto-emulator-moltest
    dfir_deploy_adx_port: 8090
    dfir_deploy_adx_python_path: "{{ (playbook_dir + '/../../../../../../../python') | realpath }}"
  tasks:
    - name: "converge | run dfir_deploy_adx"
      ansible.builtin.include_role:
        name: dfir_deploy_adx
