---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    dfir_detect_adx_processed_dir: /tmp/dfir_detect_adx_molecule/processed
    dfir_detect_adx_only: sig-hayabusa-high
    dfir_detect_adx_python_path: "{{ (playbook_dir + '/../../../../../../../python') | realpath }}"
  tasks:
    - name: "converge | run dfir_detect_adx"
      ansible.builtin.include_role:
        name: dfir_detect_adx
