---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    dfir_zimmerman_pipeline: elastic
    dfir_zimmerman_input_dir: /tmp/dfir_zimmerman_molecule/in
    dfir_zimmerman_vm_dir: /tmp/dfir_zimmerman_molecule/vm
    dfir_zimmerman_elastic_out_dir: /tmp/dfir_zimmerman_molecule/out
  tasks:
    - name: "converge | run dfir_zimmerman (elastic)"
      ansible.builtin.include_role:
        name: get_sybers.dfir.dfir_zimmerman
