---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    dxdfir_volatility_pipeline: elastic
    dxdfir_volatility_memory_dir: /tmp/dxdfir_volatility_molecule/mem
    dxdfir_volatility_elastic_out_dir: /tmp/dxdfir_volatility_molecule/out
  tasks:
    - name: "converge | run dxdfir_volatility (elastic)"
      ansible.builtin.include_role:
        name: dxdfir_volatility
