---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    dxdfir_zimmerman_pipeline: elastic
    dxdfir_zimmerman_input_dir: /tmp/dxdfir_zimmerman_molecule/in
    dxdfir_zimmerman_vm_dir: /tmp/dxdfir_zimmerman_molecule/vm
    dxdfir_zimmerman_elastic_out_dir: /tmp/dxdfir_zimmerman_molecule/out
  tasks:
    - name: "converge | run dxdfir_zimmerman (elastic)"
      ansible.builtin.include_role:
        name: dxdfir_zimmerman
