# Splunk app configuration file

[install]
is_configured = 0

[ui]
is_visible = 1
label = Kape_App

[launcher]
author = get-sybers
description = Field extraction and sourcetyping for KAPE CSV and JSON output.
version = 0.2.0
