# Splunk app configuration file

[install]
is_configured = 0

[ui]
is_visible = 1
label = BASELINE

[launcher]
author = get-sybers
description = Host and network baselining reference material and lookups for DFIR triage.
version = 0.2.0
