---
- name: Cleanup
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "molecule-cleanup | tear the stack down"
      community.docker.docker_compose_v2:
        project_src: "{{ (playbook_dir + '/../../../../../../../docker/sof-elk') | realpath }}"
        env_files: [/tmp/dfir_deploy_sofelk_molecule/sofelk.env]
        state: absent
        remove_volumes: true
