---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    molecule_sofelk_image: ""
    dfir_deploy_sofelk_image: "{{ molecule_sofelk_image }}"
    dfir_deploy_sofelk_container: sof-elk-moltest
    dfir_deploy_sofelk_ingest_dir: /tmp/dfir_deploy_sofelk_molecule/ingest
    dfir_deploy_sofelk_kibana_port: 5699
  tasks:
    - name: "converge | run dfir_deploy_sofelk"
      ansible.builtin.include_role:
        name: dfir_deploy_sofelk
