---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    dfir_deploy_sofelk_ingest_dir: /tmp/dfir_deploy_sofelk_molecule/ingest
    dfir_deploy_sofelk_env_file: /tmp/dfir_deploy_sofelk_molecule/sofelk.env
  tasks:
    - name: "converge | run dfir_deploy_sofelk"
      ansible.builtin.include_role:
        name: get_sybers.dfir.dfir_deploy_sofelk
