---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    dxdfir_deploy_sofelk_ingest_dir: /tmp/dxdfir_deploy_sofelk_molecule/ingest
    dxdfir_deploy_sofelk_env_file: /tmp/dxdfir_deploy_sofelk_molecule/sofelk.env
  tasks:
    - name: "converge | run dxdfir_deploy_sofelk"
      ansible.builtin.include_role:
        name: dxdfir_deploy_sofelk
