# detect_port_scans_horizontal.conf
# Identifies horizontal port scans by monitoring unique destination ports per source IP

[Detect_Port_Scans_Horizontal]
action.email.useNSSubject = 1
alert.track = 1
alert.expires = 7d
alert.severity = 4
alert.suppressMenu = 0
alert.suppressPriority = 1
counttype = number of events
cron_schedule = 10 * * * *
description = Identifies horizontal port scans by monitoring unique destination ports per source IP
dispatch.earliest_time = -15m
dispatch.latest_time = now
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.show = 0
enableSched = 1
quantity = 0
relation = greater than
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = index=zeek sourcetype="bro:conn:json"\
        | stats count by id.orig_h, id.resp_h, id.resp_p\
        | stats dc(id.resp_p) as unique_ports by id.orig_h, id.resp_h\
        | where unique_ports > 10\
        | rename id.orig_h as "Source IP", id.resp_h as "Destination IP", unique_ports as "Unique Ports Scanned"\
        | sort - "Unique Ports Scanned"