# detect_icmp_scans_ping_sweeps.conf
# Detects potential network discovery activities by monitoring ICMP echo requests

[Detect_ICMP_Scans_Ping_Sweeps]
action.email.useNSSubject = 1
alert.track = 1
alert.expires = 7d
alert.severity = 4
alert.suppressMenu = 0
alert.suppressPriority = 1
counttype = number of events
cron_schedule = 15 * * * *
description = Detects potential network discovery activities by monitoring ICMP echo requests
dispatch.earliest_time = -15m
dispatch.latest_time = now
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.show = 0
enableSched = 1
quantity = 0
relation = greater than
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = index=zeek sourcetype="bro:conn:json"\
        | search icmp_type=8\
        | stats count by id.orig_h, id.resp_h\
        | rename id.orig_h as "Source IP", id.resp_h as "Destination IP", count as "Ping Count"\
        | where "Ping Count" > 10\
        | sort - "Ping Count"