# detect_outbound_traffic.conf
# Identifies traffic to unknown subnets by comparing against a baseline

[Detect_Outbound_Traffic]
action.email.useNSSubject = 1
alert.track = 1
alert.expires = 7d
alert.severity = 3
alert.suppressMenu = 0
alert.suppressPriority = 1
counttype = number of events
cron_schedule = 45 * * * *
description = Identifies traffic to unknown subnets by comparing against a baseline
dispatch.earliest_time = -15m
dispatch.latest_time = now
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.show = 0
enableSched = 1
quantity = 0
relation = greater than
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = # Load the baseline lookup table\
        | inputlookup Baseline_DomainName_ClientName_ClientIP.csv\
        | table Client_IP\
        | rename Client_IP as known_subnet\
\
        # Join with conn log to flag unknown subnets\
        | join type=outer [ search index=zeek sourcetype="bro:conn:json"\
        | eval orig_subnet=mvindex(split(id.orig_h, "."), 0) . "." . mvindex(split(id.orig_h, "."), 1)\
        | eval resp_subnet=mvindex(split(id.resp_h, "."), 0) . "." . mvindex(split(id.resp_h, "."), 1)\
        | fields id.orig_h, orig_subnet, id.resp_h, resp_subnet ]\
\
        # Identify unknown subnets\
        | eval is_known_orig_subnet=if(orig_subnet IN (known_subnet), "yes", "no")\
        | eval is_known_resp_subnet=if(resp_subnet IN (known_subnet), "yes", "no")\
        | where is_known_orig_subnet="no" OR is_known_resp_subnet="no"\
        | table id.orig_h, id.orig_p, id.resp_h, id.resp_p, proto, service, conn_state