# detect_authentication_anomalies.conf
# Detects authentication anomalies by comparing against baseline login patterns

[Detect_Authentication_Anomalies]
action.email.useNSSubject = 1
alert.track = 1
alert.expires = 7d
alert.severity = 5
alert.suppressMenu = 0
alert.suppressPriority = 1
counttype = number of events
cron_schedule = 5 * * * *
description = Detects authentication anomalies by comparing against baseline login patterns
dispatch.earliest_time = -15m
dispatch.latest_time = now
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.show = 0
enableSched = 1
quantity = 0
relation = greater than
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = index=bro sourcetype=bro_kerberos client!=""\
| rex field=client (?<DomainUser>"^(.*)/") | rex field=client (?<DomainName>"[^\/]([^/]+)$")\
| eval Time=strftime(_time, "%Y-%m-%d %H:%M:%S") | eval DomainName=upper(DomainName)\
| lookup Base-UsualLoginHours.csv DomainName\
| eval UsualLoginHours=Hour | eval HourlyThresholdForDomain=mvindex(HourlyThreshold,0)\
| rex field=Time ".+ (?<LoginHour>.{2})" | eval LoginHour=LoginHour+":00"\
| table Time LoginHour UsualLoginHours DomainName DomainUser HourlyThresholdForDomain\
| foreach UsualLoginHours [eval IsUsualHour=if(LoginHour==UsualLoginHours, 1, 0)] | search IsUsualHour=0\
| stats count by DomainName LoginHour HourlyThresholdForDomain\
| eval IsOverThreshold=if(count>HourlyThresholdForDomain, 1, 0) | search IsOverThreshold=1