# detect_new_host_or_ip.conf
# Identifies new Client_IP or Client_Name on the network by comparing current DNS data against a baseline

[Detect_New_Host_Or_IP]
action.email.useNSSubject = 1
alert.track = 1
alert.expires = 7d
alert.severity = 3
alert.suppressMenu = 0
alert.suppressPriority = 1
counttype = number of events
cron_schedule = 30 * * * *
description = Identifies new Client_IP or Client_Name on the network by comparing current DNS data against a baseline
dispatch.earliest_time = -15m
dispatch.latest_time = now
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.show = 0
enableSched = 1
quantity = 0
relation = greater than
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = # Load the baseline lookup table\
        | inputlookup Baseline_DomainName_ClientName_ClientIP.csv\
        | rename Client_IP as known_Client_IP, Client_Name as known_Client_Name\
\
        # Extract current Client_IPs and Client_Names from DNS logs\
        | multisearch\
            [ search index=powershell "Command.Module"=GetDomainComputers\
              | rex field=Data.DNSName "^(?<Client_Name>[^.]+)"\
              | rex field=Data.DNSName "^[^.]+\.(?<Domain_Name>.+)"\
              | eval source = "powershell"\
              | eval Client_IP=Data.IPAddress ]\
            [ search index=zeek sourcetype="bro:dns:json" query!="*\.arpa" query!="" answers!="0.0.0.0" query!="0.0.0.0"\
              | rex field=answers "(?<Client_IP>\b(?:\d{1,3}\.){3}\d{1,3}\b)"\
              | rex field=query "^(?<Client_Name>[^.]+)"\
              | rex field=query "^[^.]+\.(?<Domain_Name>.+)"\
              | eval source="zeek" ]\
        | eval Domain_Name=upper(Domain_Name), Client_IP=upper(Client_IP), Client_Name=upper(Client_Name)\
        | dedup Domain_Name, Client_IP, Client_Name, source\
\
        # Identify new Client_IPs or Client_Names not in the baseline\
        | join type=left Client_IP [ | inputlookup Baseline_DomainName_ClientName_ClientIP.csv ]\
        | where isnull(known_Client_IP)\
        | table Domain_Name, Client_IP, Client_Name, source