---
- name: Check for required restarts
  splunk_api:
    method: GET
    url: "/services/messages/restart_required?output_mode=json"
    username: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    status_code: [200, 404]
    svc_port: "{{ splunk.svc_port }}"
    cert_prefix: "{{ cert_prefix }}"
  register: restart_required
  changed_when: restart_required.status == 200
  until: restart_required is succeeded
  retries: 5
  delay: "{{ retry_delay }}"
  notify:
    - Restart the splunkd service
