---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    dfir_volatility_pipeline: elastic
    dfir_volatility_memory_dir: /tmp/dfir_volatility_molecule/mem
    dfir_volatility_elastic_out_dir: /tmp/dfir_volatility_molecule/out
  tasks:
    - name: "converge | run dfir_volatility (elastic)"
      ansible.builtin.include_role:
        name: get_sybers.dfir.dfir_volatility
