# Splunk app configuration file

[install]
is_configured = 0

[ui]
is_visible = 1
label = EvtxECmd_App

[launcher]
author = get-sybers
description = Field extraction for EvtxECmd output, mapped to the Splunk Add-on for Microsoft Windows schema.
version = 0.1.0
