---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    dfir_velociraptor_pipeline: adx
    dfir_velociraptor_raw_dir: /tmp/dfir_velociraptor_molecule/raw
    dfir_velociraptor_adx_out_dir: /tmp/dfir_velociraptor_molecule/out
  tasks:
    - name: "converge | run dfir_velociraptor (ADX)"
      ansible.builtin.include_role:
        name: dfir_velociraptor
