[BSL_FQDN_IP]
action.email.useNSSubject = 1
action.webhook.enable_allowlist = 0
alert.track = 0
cron_schedule = 0 0 * * *
dispatch.earliest_time = -24h@h
dispatch.latest_time = now
display.events.fields = ["host","source","sourcetype","date","datetime","description","description_short","display_name","extracted_host","extracted_source","filename","extracted_sourcetype","hostname","index","inode","linecount","macb","message","punct","message_short","timezone","user","username","zone","processorArchitecture","version","publicKeyToken","scope","language","Version","versionScope","Culture","PublicKeyToken","chrome_url","crx_id","crx_name","crx_path","original_message","source_long","timestamp_desc","time","tag","LastWriteTimestamp","timestamp","kape_source_rest","kape_source_short","Computer","Channel","EventRecordId","ProcessId","EventId","Provider","ThreadId","Payload","answers","analyzers","id_orig_h","id_orig_p","id_resp_h","id_resp_p","uid","query"]
display.general.type = statistics
display.page.search.mode = verbose
display.page.search.tab = statistics
display.visualizations.show = 0
request.ui_dispatch_app = BASELINE
request.ui_dispatch_view = search
search = index=network sourcetype="zeek:dns" NOT query IN ("*default-first-site-name*", "_ldap*", "*-addr.arpa") answers!="-" AA=T\
| rename query AS FQDN, answers AS ip_address\
| stats count as new_count, earliest(_time) as new_first_seen, latest(_time) as new_last_seen by FQDN, ip_address\
| eval new_first_seen=strftime(new_first_seen, "%Y-%m-%d %H:%M:%S"), new_last_seen=strftime(new_last_seen, "%Y-%m-%d %H:%M:%S")\
| append \
    [| inputlookup BSL_FQDN_IP.csv \
     | rename count as old_count, first_seen as old_first_seen, last_seen as old_last_seen]\
| stats values(new_count) as new_count, values(old_count) as old_count, \
        values(new_first_seen) as new_first_seen, values(old_first_seen) as old_first_seen,\
        values(new_last_seen) as new_last_seen, values(old_last_seen) as old_last_seen by FQDN, ip_address\
| eval count=coalesce(new_count, 0) + coalesce(old_count, 0)\
| eval first_seen=case(\
    isnull(old_first_seen), new_first_seen,\
    isnull(new_first_seen), old_first_seen,\
    strptime(old_first_seen, "%Y-%m-%d %H:%M:%S") < strptime(new_first_seen, "%Y-%m-%d %H:%M:%S"), old_first_seen,\
    strptime(new_first_seen, "%Y-%m-%d %H:%M:%S") < strptime(old_first_seen, "%Y-%m-%d %H:%M:%S"), new_first_seen,\
    1==1, old_first_seen)\
| eval last_seen=case(\
    isnull(old_last_seen), new_last_seen,\
    isnull(new_last_seen), old_last_seen,\
    strptime(old_last_seen, "%Y-%m-%d %H:%M:%S") > strptime(new_last_seen, "%Y-%m-%d %H:%M:%S"), old_last_seen,\
    strptime(new_last_seen, "%Y-%m-%d %H:%M:%S") > strptime(old_last_seen, "%Y-%m-%d %H:%M:%S"), new_last_seen,\
    1==1, old_last_seen)\
| table FQDN, ip_address, first_seen, last_seen\
| sort FQDN, ip_address\
| outputlookup BSL_FQDN_IP.csv