# Splunk app configuration file

[install]
is_configured = 0

[ui]
is_visible = 1
label = Rekall_App

[launcher]
author = get-sybers
description = Field extraction and sourcetyping for Rekall JSON memory-analysis output.
version = 0.2.0
