# host_first_last_seen.conf
# Track when hosts were first and last seen in the environment

[Host_First_Last_Seen]
action.email.useNSSubject = 1
alert.track = 0
description = Tracks when hosts were first and last seen in the environment
dispatch.earliest_time = -30d@d
dispatch.latest_time = now
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.show = 0
enableSched = 0
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = | inputlookup hosts.csv\
| rename ip as ip_address\
| join type=inner ip_address [\
    search index=zeek_data\
    | eval ts_converted=strptime(ts, "%s")  \
    | stats earliest(ts_converted) as first_seen latest(ts_converted) as last_seen by ip_address\
    | eval first_seen=strftime(first_seen, "%Y-%m-%d %H:%M:%S")\
    | eval last_seen=strftime(last_seen, "%Y-%m-%d %H:%M:%S")\
]\
| table host_name ip_address first_seen last_seen