---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    dfir_zeek_pipeline: elastic
    dfir_zeek_pcap_dir: /tmp/dfir_zeek_molecule/pcaps
    dfir_zeek_elastic_out_dir: /tmp/dfir_zeek_molecule/out
  tasks:
    - name: "converge | run dfir_zeek (elastic)"
      ansible.builtin.include_role:
        name: dfir_zeek
