# Splunk app configuration file

[install]
is_configured = 0

[ui]
is_visible = 1
label = Log2timeline_App

[launcher]
author = get-sybers
description = Field extraction and sourcetyping for log2timeline (Plaso) dynamic CSV output.
version = 0.1.0
