[winevent_source_extraction]
REGEX=\\(?<winevent_source>[^\\]+)\.evtx
FORMAT=winevent_source::$1
WRITE_META = true

[computer_name_extraction]
REGEX=Computer Name:\s(?<computer_name>[^,\s\n]+)
FORMAT=computer_name::$1
WRITE_META = true

[event_id_extraction]
REGEX=\[(?<event_id>\d+)\s
FORMAT=event_id::$1
WRITE_META = true

[provider_extraction]
REGEX=Provider Name:\s(?<provider>[^,\s]+)
FORMAT=provider::$1
WRITE_META = true

[channel_extraction]
REGEX=Channel:\s(?<channel>[^,\s]+)
FORMAT=channel::$1
WRITE_META = true