[l2t:winevtx]
KV_MODE = none
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%f%z
TIMESTAMP_FIELDS = datetime
NO_BINARY_CHECK = true
MAX_EVENTS = 0
TRUNCATE = 0
EVAL-host = upper(host)
TRANSFORMS-winevtx_fields = winevent_source_extraction, computer_name_extraction, event_id_extraction, provider_extraction, channel_extraction