# Splunk app configuration file

[install]
is_configured = 0

[ui]
is_visible = 1
label = Velociraptor_App

[launcher]
author = get-sybers
description = Velociraptor JSON output ingestion for DFIR analysis
version = 0.1.0
