#############################################################################################
#                                   Velociraptor JSON                                       #
#############################################################################################
[velociraptor:json]
MAX_DAYS_AGO = 10000
# Parsing and performance settings based on Splunk recommended VQL artifact configuration
INDEXED_EXTRACTIONS = json
DATETIME_CONFIG = CURRENT
TZ = GMT
category = Custom
pulldown_type = 1
TRANSFORMS-vql-sourcetype = vql_sourcetype, vql_timestamp
TRUNCATE = 512000
KV_MODE = none
AUTO_KV_JSON = false
SHOULD_LINEMERGE = false
